config/routes.rb
Praqtic::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :lessons
    end
  end

  resources :users, except: :new
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    resources :friends, controller: 'category_friendships'
    resources :parents, controller: 'category_relations'
  end
  resources :quizzes do
    resources :questions do
      resources :interactions, controller: 'question_interactions'
    end
    resources :lessons
    resources :prereqs, controller: 'quiz_dependencies'
    resources :postreqs, controller: 'quiz_dependencies'
    get 'do', on: :member
    post 'submit_question', on: :member
    get 'report', on: :member
  end
  resources :classifications
  resources :graph

  root 'pages#home'

  get '/signup'  => 'users#new'
  get '/signin'  => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help'    => 'pages#help'
  get '/about'   => 'pages#about'
  get '/contact' => 'pages#contact'

  get '/admin'   => 'admin#index'
  get '/admin/category/:id' => 'admin#category', as: :admin_category
  get '/admin/quiz/:id' => 'admin#quiz', as: :admin_quiz
  get '/admin/lesson/:id' => 'admin#lesson', as: :admin_lesson
  delete '/admin/destroy/:klass/:id'  => 'admin#destroy', as: :admin_destroy
  delete '/admin/destroy_multiple'    =>  'admin#destroy_multiple'

  post '/feed_questions/submit'          =>  'feed#submit_answer'

end

app/views/admin/_category.html.erb
<tr id='tag_<%= category.friendly_id %>' class='tr-url' url='<%= admin_category_path(category) %>'>
  <td><%= check_box_tag "categories[]", category.id %></td>
  <td><%= category.name %></td>
  <td><%= category.creator ? category.creator.name : 'nil' %></td>
  <td><%= category.quizzes.size %></td>
  <td><%= category.lessons.size %></td>
  <td>
    <%= link_to 'Delete Tag', admin_destroy_path('tag', category.id), data: { confirm: 'Are you sure you want to delete this tag?' }, :method => :delete, :remote => true, class: 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/admin/_lesson.html.erb
<tr id='source<%= lesson.friendly_id %>' class='tr-url' url='<%= admin_lesson_path(lesson) %>'>
  <td><%= check_box_tag "lessons[]", lesson.id %></td>
  <td><%= lesson.name %></td>
  <td><%= lesson.creator ? lesson.creator.name : 'nil' %></td>
  <td><%= lesson.quizzes.size %></td>
  <td><%= lesson.questions.size %></td>
  <td>
    <%= link_to 'Delete Source', admin_destroy_path('source', lesson.id), data: { confirm: 'Are you sure you want to delete this source?' }, :method => :delete, :remote => true, class: 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/admin/_quiz.html.erb
<tr id='quiz_<%= quiz.friendly_id %>' class='tr-url' url="<%= admin_quiz_path(quiz) %>">
  <td><%= check_box_tag "quizzes[]", quiz.id %></td>
  <td><%= quiz.name %></td>
  <td><%= quiz.creator ? quiz.creator.name : 'nil' %></td>
  <td><%= quiz.questions.size %></td>
  <td><%= quiz.lessons.size %></td>
  <td>
    <%= link_to 'Delete Quiz', admin_destroy_path('quiz', quiz.id), data: { confirm: 'Are you sure you want to delete this quiz?' }, :method => :delete, :remote => true, class: 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/admin/category.html.erb
<% provide(:title, 'Admin::' + @category.name) %>

<h1><%= @category.name %> </h1>
<br />
<div class="row text-center">
  <%= link_to 'Delete Tag', admin_destroy_path('tag', @category.id), :confirm => 'Are you sure you want to delete this tag?', :method => :delete, class: 'btn btn-mini btn-danger' %>
</div>

app/views/admin/destroy.js.erb
$('#<%= @klass + "_" + @object.friendly_id %>').fadeOut(200, function() {
    $(this).remove();
  });

app/views/admin/destroy_multiple.js.erb
<% @quizzes.each do |q| %>
<% puts 'DEBUG1 ' + q.name %>

  $('#quiz_<%= q.friendly_id %>').fadeOut(200, function() {
      $(this).remove();
    });

<% end %>

<% @lessons.each do |l| %>
<% puts 'DEBUG1 ' + l.name %>

  $('#source_<%= l.friendly_id %>').fadeOut(200, function() {
      $(this).remove();
    });

<% end %>

<% @categories.each do |c| %>
<% puts 'DEBUG1 ' + c.name %>

  $('#tag_<%= c.friendly_id %>').fadeOut(200, function() {
      $(this).remove();
    });

<% end %>

app/views/admin/index.html.erb
<% provide(:title, 'Admin') %>

<h1>Admin</h1>

<%= form_tag admin_destroy_multiple_path, :method => :delete, :remote => true do %>

  <h3 class='text-center'>Tags</h3>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Select</th><th>Name</th><th>Creator</th><th>Quizzes</th><th>Lessons</th><th>Remove</th>
      </tr>
    </thead>
    <%= render :partial => 'category', :collection => @categories %>
  </table>

  <%= submit_tag "Delete selected" %>

  <h3 class='text-center'>Quizzes</h3>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Select</th><th>Name</th><th>Creator</th><th>Questions</th><th>Lessons</th><th>Remove</th>
      </tr>
    </thead>
    <%= render :partial => 'quiz', :collection => @quizzes %>
  </table>

  <%= submit_tag "Delete selected" %>

  <h3 class='text-center'>Sources</h3>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Select</th><th>Name</th><th>Creator</th><th>Quizzes</th><th>Questions</th><th>Remove</th>
      </tr>
    </thead>
    <%= render :partial => 'lesson', :collection => @lessons %>
  </table>

  <%= submit_tag "Delete selected" %>

<% end %>

app/views/admin/lesson.html.erb
<% provide(:title, 'Admin::' + @lesson.name) %>

<h1><%= @lesson.name %> </h1>
<br />
<div class="row text-center">
  <%= link_to 'Delete Source', admin_destroy_path('source', @lesson.id), :confirm => 'Are you sure you want to delete this source?', :method => :delete, class: 'btn btn-mini btn-danger' %>
</div>

app/views/admin/quiz.html.erb
<% provide(:title, 'Admin::' + @quiz.name) %>

<h1><%= @quiz.name %> </h1>
<br />
<div class="row text-center">
  <%= link_to 'Delete Quiz', admin_destroy_path('quiz', @quiz.id), :confirm => 'Are you sure you want to delete this quiz?', :method => :delete, class: 'btn btn-mini btn-danger' %>
</div>