config/routes.rb
Praqtic::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :lessons
    end
  end

  resources :users, except: :new
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    resources :friends, controller: 'category_friendships'
    resources :parents, controller: 'category_relations'
  end
  resources :quizzes do
    resources :questions do
      resources :interactions, controller: 'question_interactions'
    end
    resources :lessons
    resources :prereqs, controller: 'quiz_dependencies'
    resources :postreqs, controller: 'quiz_dependencies'
    get 'do', on: :member
    post 'submit_question', on: :member
    get 'report', on: :member
  end
  resources :classifications
  resources :graph

  root 'pages#home'

  get '/signup'  => 'users#new'
  get '/signin'  => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help'    => 'pages#help'
  get '/about'   => 'pages#about'
  get '/contact' => 'pages#contact'

  get '/admin'   => 'admin#index'
  get '/admin/category/:id' => 'admin#category', as: :admin_category
  get '/admin/quiz/:id' => 'admin#quiz', as: :admin_quiz
  get '/admin/lesson/:id' => 'admin#lesson', as: :admin_lesson
  delete '/admin/destroy/:klass/:id'  => 'admin#destroy', as: :admin_destroy
  delete '/admin/destroy_multiple'    =>  'admin#destroy_multiple'

  post '/feed_questions/submit'          =>  'feed#submit_answer'

end

app/controllers/question_interactions_controller.rb
class QuestionInteractionsController < ApplicationController
  before_action :set_question_interaction, only: [:show, :edit, :update, :destroy]

  # GET /question_interactions
  # GET /question_interactions.json
  def index
    @question_interactions = QuestionInteraction.all
  end

  # GET /question_interactions/1
  # GET /question_interactions/1.json
  def show
  end

  # GET /question_interactions/new
  def new
    @question_interaction = QuestionInteraction.new
  end

  # GET /question_interactions/1/edit
  def edit
  end

  # POST /question_interactions
  # POST /question_interactions.json
  def create
    @question_interaction = QuestionInteraction.new(question_interaction_params)

    respond_to do |format|
      if @question_interaction.save
        format.html { redirect_to @question_interaction, notice: 'Question interaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question_interaction }
      else
        format.html { render action: 'new' }
        format.json { render json: @question_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_interactions/1
  # PATCH/PUT /question_interactions/1.json
  def update
    respond_to do |format|
      if @question_interaction.update(question_interaction_params)
        format.html { redirect_to @question_interaction, notice: 'Question interaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_interactions/1
  # DELETE /question_interactions/1.json
  def destroy
    @question_interaction.destroy
    respond_to do |format|
      format.html { redirect_to question_interactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_interaction
      @question_interaction = QuestionInteraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_interaction_params
      params[:question_interaction]
    end
end

app/helpers/question_interactions_helper.rb
module QuestionInteractionsHelper
end

app/views/question_interactions/_form.html.erb
<%= form_for(@question_interaction) do |f| %>
  <% if @question_interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_interaction.errors.count, "error") %> prohibited this question_interaction from being saved:</h2>

      <ul>
      <% @question_interaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_interactions/edit.html.erb
<h1>Editing question_interaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_interaction %> |
<%= link_to 'Back', question_interactions_path %>

app/views/question_interactions/index.html.erb
<h1>Listing question_interactions</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @question_interactions.each do |question_interaction| %>
      <tr>
        <td><%= link_to 'Show', question_interaction %></td>
        <td><%= link_to 'Edit', edit_question_interaction_path(question_interaction) %></td>
        <td><%= link_to 'Destroy', question_interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question interaction', new_question_interaction_path %>

app/views/question_interactions/new.html.erb
<h1>New question_interaction</h1>

<%= render 'form' %>

<%= link_to 'Back', question_interactions_path %>

app/views/question_interactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_interaction_path(@question_interaction) %> |
<%= link_to 'Back', question_interactions_path %>