config/routes.rb
Praqtic::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :lessons
    end
  end

  resources :users, except: :new
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    resources :friends, controller: 'category_friendships'
    resources :parents, controller: 'category_relations'
  end
  resources :quizzes do
    resources :questions do
      resources :interactions, controller: 'question_interactions'
    end
    resources :lessons
    resources :prereqs, controller: 'quiz_dependencies'
    resources :postreqs, controller: 'quiz_dependencies'
    get 'do', on: :member
    post 'submit_question', on: :member
    get 'report', on: :member
  end
  resources :classifications
  resources :graph

  root 'pages#home'

  get '/signup'  => 'users#new'
  get '/signin'  => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help'    => 'pages#help'
  get '/about'   => 'pages#about'
  get '/contact' => 'pages#contact'

  get '/admin'   => 'admin#index'
  get '/admin/category/:id' => 'admin#category', as: :admin_category
  get '/admin/quiz/:id' => 'admin#quiz', as: :admin_quiz
  get '/admin/lesson/:id' => 'admin#lesson', as: :admin_lesson
  delete '/admin/destroy/:klass/:id'  => 'admin#destroy', as: :admin_destroy
  delete '/admin/destroy_multiple'    =>  'admin#destroy_multiple'

  post '/feed_questions/submit'          =>  'feed#submit_answer'

end

app/models/category.rb
# A category object represents a named collection of related quizzes. Through categories, we can
# represent hierarchical fields of knowledge, and allow the user to browse the tree of knowledge.
#
# Each category may belong to one or more parent categories, and may have one or more subcategories.
#    - when you are learning (spanish conjugation) you are learning (spanish language)
#    - when you are learning (spanish conjugation) you are learning (conjugation)
#    - when you are learning (conjugation) you are learning (grammar)
#
# Categories that are related but do not fit in a parent-child relationship can be linked as friend
# nodes. This relationship indicates that learning content from one category will enrich your
# knowledge of another.
#    - learning (resonance [physics]) enriches knowledge of (harmonic series [music])
#
# Each category may contain one or more quizzes. While most quizzes will be contained by
# category "leaves," it is possible for a category to have subcategories and to also have its own
# content which fits in the category but not in any of its subcategories.

class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  # parent-child association
  has_many :parent_relations, class_name: "CategoryRelation", foreign_key: "child_id"
  has_many :parents, through: :parent_relations, class_name: "Category"

  has_many :child_relations, class_name: "CategoryRelation", foreign_key: "parent_id"
  has_many :children, through: :child_relations, class_name: "Category"

  # friend associaton
  has_many :friendships, class_name: "CategoryFriendship"
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "CategoryFriendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :category

  # content association
  has_many :classifications, :inverse_of => :category, dependent: :destroy
  has_many :quizzes, through: :classifications
  has_many :lessons, :through => :quizzes

  belongs_to :creator, :class_name => "User"

  # validations
  validates :name,  presence: true, length: { maximum: 50 }
  validates_presence_of :slug, :creator

  # sorting
  default_scope { order(created_at: :asc) }

  # before_validation :logBV
  # after_validation :logAV
  # before_save :logBS
  # after_save :logAS
  # before_create :logBC
  # after_create :logAC
  # after_commit :logACommit
  # after_rollback :logAR
  # after_touch :logAT


  def logBV
    logger.error "cat BEFORE VALIDATION"
  end
  def logAV
    logger.error "cat AFTER VALIDATION"
  end
  def logBS
    logger.error "cat BEFORE SAVE"
  end
  def logAS
    logger.error "cat AFTER SAVE"
  end
  def logBC
    logger.error "cat BEFORE CREATE"
  end
  def logAC
    logger.error "cat AFTER CREATE"
  end
  def logACommit
    logger.error "cat AFTER COMMIT"
  end
  def logAR
    logger.error "cat AFTER ROLLBACK"
  end
  def logAT
    logger.error "cat AFTER TOUCH"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @root_node = Category.first
  end

  def show
  end

  def new
    @parent = Category.friendly.find(params[:parent])
  end

  def create
    @category.creator = current_user

    @parent = Category.friendly.find(params[:parent])
    if @parent.nil?
      @parent = Category.first
    end

    @relation = CategoryRelation.new(:parent => @parent, :child => @category)

    # puts 'Cat: ' + @category.name + ' Parent: ' + @parent.name

    if @relation.save && @category.save
      flash[:success] = "Category created!"
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "Category removed."
    redirect_to categories_path
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% recursive ||= false %>
<li>
  <%= link_to category.name, category_path(category) %>

  <% if recursive %>
    <ul class="categories">
      <%= render category.children, recursive: recursive %>
    </ul>
  <% end %>
</li>

app/views/categories/_fields.html.erb
<%= render 'shared/error_messages', object: @category  %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= hidden_field_tag 'parent', @parent.id %>

app/views/categories/index.html.erb
<% provide(:title, 'All Categories') %>
<h1>All Categories</h1>



<% if @root_node %>
<ul class="categories">
  <%= render @root_node, recursive: true %>
</ul>
<% end %>

app/views/categories/new.html.erb
<% provide(:title, 'New Subcategory') %>
<h1>Create New Subcategory</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@category, url: categories_path) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Add Subcategory", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>
<div class="row">

  <h1>
    <%= @category.name %>
  </h1>

  <section class="span3">
    <h2 style="text-align:left;">Parent Categories:</h2>
    <% if @category.parents.count > 0 %>
      <ul class="parents">
        <%= render @category.parents %>
      </ul>
      <%= link_to "+ Add Parent", new_category_parent_path(@category) %>
    <% else %>
      <p>This is the root of all knowledge.</p>
    <% end %>
  </section>

  <section class="span3">
    <h2 style="text-align:left;">Subcategories:</h2>
    <% if @category.children.count > 0 %>
      <ul class="categories">
        <%= render @category.children %>
      </ul>
    <% else %>
      <p>This category doesn't have any subcategories. Add one!</p>
    <% end %>

      <%= link_to "+ Add Subcategory", new_category_path(parent: @category) %>
  </section>

  <section class="span3">
    <h2 style="text-align:left;">Friend Categories:</h2>
    <% if @category.friends.count > 0 %>
      <ul class="friends">
        <%= render @category.friends %>
      </ul>
    <% else %>
      <p>This category doesn't have any friend categories. Add one!</p>
    <% end %>

      <%= link_to "+ Add Friendship", new_category_friend_path(@category) %>
  </section>

  <section class="span3">
    <h2 style="text-align:left;">Content:</h2>

    <% if @category.quizzes.count > 0 %>
      <ul class="quizzes">
        <%= render @category.quizzes %>
      </ul>
    <% else %>
      <p>This category doesn't contain any quizzes. Add one!</p>
    <% end %>

      <%= link_to "+ Add Quiz", new_quiz_path(category: @category) %>
  </section>

</div>