config/routes.rb
Praqtic::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :lessons
    end
  end

  resources :users, except: :new
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    resources :friends, controller: 'category_friendships'
    resources :parents, controller: 'category_relations'
  end
  resources :quizzes do
    resources :questions do
      resources :interactions, controller: 'question_interactions'
    end
    resources :lessons
    resources :prereqs, controller: 'quiz_dependencies'
    resources :postreqs, controller: 'quiz_dependencies'
    get 'do', on: :member
    post 'submit_question', on: :member
    get 'report', on: :member
  end
  resources :classifications
  resources :graph

  root 'pages#home'

  get '/signup'  => 'users#new'
  get '/signin'  => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help'    => 'pages#help'
  get '/about'   => 'pages#about'
  get '/contact' => 'pages#contact'

  get '/admin'   => 'admin#index'
  get '/admin/category/:id' => 'admin#category', as: :admin_category
  get '/admin/quiz/:id' => 'admin#quiz', as: :admin_quiz
  get '/admin/lesson/:id' => 'admin#lesson', as: :admin_lesson
  delete '/admin/destroy/:klass/:id'  => 'admin#destroy', as: :admin_destroy
  delete '/admin/destroy_multiple'    =>  'admin#destroy_multiple'

  post '/feed_questions/submit'          =>  'feed#submit_answer'

end

app/controllers/quiz_dependencies_controller.rb
class QuizDependenciesController < ApplicationController
  skip_authorization_check #todo: i have no idea how authorization works, we need to chat. -cf

  include GraphHelper

  def new
    # @jsonNodes = category_to_node(Category.first).to_json

    # quiz = Quiz.find(params[:quiz_id])

    # current_uri = request.fullpath

    # if (current_uri.index('prereq'))
    #   @dependency = quiz.dependencies.build
    # else
    #   @dependency = quiz.post_dependencies.build
    # end
  end

  def create
    # quiz = Quiz.find(params[:quiz_id])

    # current_uri = request.fullpath
    # if (current_uri.index('prereq'))
    #   prereq = Quiz.find(params[:dependency][:prereq])
    #   postreq = quiz
    # else
    #   prereq = quiz
    #   postreq = Quiz.find(params[:dependency][:postreq])
    # end

    # @dependency = Dependency.new(:prereq => prereq, :postreq => postreq)

    # if (@dependency.save)
    #   flash[:success] = "Dependency created!"
    #   redirect_to quiz
    # else
    #   render 'new'
    # end
  end
end

app/helpers/quiz_dependencies_helper.rb
module QuizDependenciesHelper
end

app/views/quiz_dependencies/new.html.erb
<h1 id="header">Select a category to show quizzes</h1>

<% if (request.fullpath.index('prereq')) %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for([@dependency.prereq, @dependency], url: quiz_prereqs_path) do |f| %>
      <%= f.hidden_field :postreq, :value => @dependency.postreq.id %>
      <%= f.hidden_field :prereq %>
      <%= f.submit "Create Necessity", class: "btn btn-large btn-primary", id: "submit-button" %>
    <% end %>
  </div>
</div>

<% else %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for([@dependency.postreq, @dependency], url: quiz_postreqs_path) do |f| %>
      <%= f.hidden_field :prereq, :value => @dependency.prereq.id %>
      <%= f.hidden_field :postreq %>
      <%= f.submit "Create Possibility", class: "btn btn-large btn-primary", id: "submit-button" %>
    <% end %>
  </div>
</div>

<% end %>

<!-- this is the element our script attaches the SVG element to -->
<div id="graph"></div>

<script>

  d3.selectAll("#submit-button").style("display", "none");

  var data = <%= raw(@jsonNodes) %>

  function categoryClickFunction(d) {
    d3.selectAll("#header").text("Select a quiz");

    d3.selectAll("g.node").classed("active", false);
    d3.select(this).classed("active", true);

    graph.showQuizzes(d);
  };

  function quizClickFunction(d) {

    d3.selectAll("g.node").classed("active", false);
    d3.select(this).classed("active", true);

    <% if (request.fullpath.index('prereq')) %>

    d3.selectAll("#header").text("Add " + d.name + " as a necessity to <%= @dependency.postreq.name %>?");
    d3.selectAll("#dependency_prereq").property("value", d.id);

    <% else %>

    d3.selectAll("#header").text("Add " + d.name + " as a possibility to <%= @dependency.prereq.name %>?");
    d3.selectAll("#dependency_postreq").property("value", d.id);

    <% end %>

    d3.selectAll("#submit-button").style("display", "block");
  };

  var graph = CategoryGraph();
  graph("#graph", data);
  graph.categoryNodeOnClick(categoryClickFunction);
  graph.quizNodeOnClick(quizClickFunction);

</script>